# Generated by Django 5.2.11 on 2026-02-03 17:34

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Neighborhood",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        choices=[("DOUALA", "Douala"), ("YAOUNDE", "Yaoundé")],
                        max_length=20,
                        verbose_name="Ville",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nom du quartier"),
                ),
                (
                    "center_geo",
                    django.contrib.gis.db.models.fields.PointField(
                        srid=4326, verbose_name="Centre du quartier (GPS)"
                    ),
                ),
                (
                    "radius_km",
                    models.FloatField(
                        default=1.5, verbose_name="Rayon approximatif (km)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Quartier",
                "verbose_name_plural": "Quartiers",
                "ordering": ["city", "name"],
                "unique_together": {("city", "name")},
            },
        ),
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "recipient_phone",
                    models.CharField(
                        max_length=15, verbose_name="Téléphone destinataire"
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Nom destinataire"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("ASSIGNED", "Coursier assigné"),
                            ("PICKED_UP", "Colis récupéré"),
                            ("IN_TRANSIT", "En transit"),
                            ("COMPLETED", "Livré"),
                            ("CANCELLED", "Annulé"),
                            ("FAILED", "Échec livraison"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH_P2P", "Cash (Client → Coursier)"),
                            ("PREPAID_WALLET", "Prépayé (Wallet Marchand)"),
                        ],
                        default="CASH_P2P",
                        max_length=20,
                        verbose_name="Méthode de paiement",
                    ),
                ),
                (
                    "pickup_geo",
                    django.contrib.gis.db.models.fields.PointField(
                        srid=4326, verbose_name="Point de ramassage (GPS)"
                    ),
                ),
                (
                    "pickup_address",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Adresse ramassage (optionnel)",
                    ),
                ),
                (
                    "dropoff_geo",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        null=True,
                        srid=4326,
                        verbose_name="Point de livraison (GPS)",
                    ),
                ),
                (
                    "dropoff_address",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Adresse livraison (optionnel)",
                    ),
                ),
                (
                    "package_description",
                    models.TextField(blank=True, verbose_name="Description du colis"),
                ),
                (
                    "package_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="packages/",
                        verbose_name="Photo du colis",
                    ),
                ),
                (
                    "distance_km",
                    models.FloatField(default=0.0, verbose_name="Distance (km)"),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Prix total (XAF)",
                    ),
                ),
                (
                    "platform_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Commission plateforme (XAF)",
                    ),
                ),
                (
                    "courier_earning",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Gain coursier (XAF)",
                    ),
                ),
                (
                    "otp_code",
                    models.CharField(
                        blank=True, max_length=4, verbose_name="Code OTP livraison"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("picked_up_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "external_order_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ID commande externe"
                    ),
                ),
                (
                    "courier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_deliveries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Coursier",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sent_deliveries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Expéditeur",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shop_deliveries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Boutique (B2B)",
                    ),
                ),
                (
                    "dropoff_neighborhood",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="logistics.neighborhood",
                        verbose_name="Quartier livraison (si pas de GPS)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Livraison",
                "verbose_name_plural": "Livraisons",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="logistics_d_status_7c2c4e_idx",
                    ),
                    models.Index(
                        fields=["courier", "status"],
                        name="logistics_d_courier_8f604d_idx",
                    ),
                ],
            },
        ),
    ]
