# Generated by Django 5.2.11 on 2026-02-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="in_transit_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="delivery",
            name="proof_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="proofs/",
                verbose_name="Photo preuve de livraison",
            ),
        ),
    ]
