# Generated by Django 5.2.11 on 2026-02-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0002_add_tracking_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="pickup_otp",
            field=models.CharField(
                blank=True, max_length=4, verbose_name="Code OTP retrait"
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="pickup_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="pickups/",
                verbose_name="Photo du colis au retrait",
            ),
        ),
    ]
