# Generated by Django 5.2.11 on 2026-02-05 18:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0003_add_pickup_validation_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating_type",
                    models.CharField(
                        choices=[
                            ("COURIER", "Client → Coursier"),
                            ("SENDER", "Coursier → Client"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        help_text="Note de 1 (mauvais) à 5 (excellent)",
                        verbose_name="Note (1-5)",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Commentaire")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="logistics.delivery",
                        verbose_name="Livraison",
                    ),
                ),
                (
                    "rated",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Évalué",
                    ),
                ),
                (
                    "rater",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings_given",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Évaluateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Évaluation",
                "verbose_name_plural": "Évaluations",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["rated", "created_at"],
                        name="logistics_r_rated_i_92a309_idx",
                    )
                ],
                "unique_together": {("delivery", "rater", "rated")},
            },
        ),
    ]
