# Generated by Django 5.2.11 on 2026-02-05 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0004_add_rating_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("CASH_P2P", "Cash (Client → Coursier)"),
                    ("PREPAID_WALLET", "Prépayé (Wallet Marchand)"),
                    ("MOBILE_MONEY", "Mobile Money (MTN/Orange)"),
                ],
                default="CASH_P2P",
                max_length=20,
                verbose_name="Méthode de paiement",
            ),
        ),
    ]
