# Generated by Django 5.2.11 on 2026-02-09 11:49

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0005_add_mobile_payment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrafficEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("ACCIDENT", "🚗 Accident"),
                            ("POLICE", "👮 Contrôle de police"),
                            ("ROAD_CLOSED", "🚧 Route barrée"),
                            ("FLOODING", "🌊 Inondation"),
                            ("POTHOLE", "🕳️ Nid-de-poule"),
                            ("TRAFFIC_JAM", "🚦 Embouteillage"),
                            ("ROADWORK", "🏗️ Travaux"),
                            ("HAZARD", "⚠️ Danger sur la route"),
                            ("FUEL_STATION", "⛽ Station essence ouverte"),
                            ("OTHER", "📍 Autre"),
                        ],
                        max_length=20,
                        verbose_name="Type d'événement",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Faible"),
                            ("MEDIUM", "Moyen"),
                            ("HIGH", "Élevé"),
                            ("CRITICAL", "Critique"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                        verbose_name="Sévérité",
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        srid=4326, verbose_name="Position GPS"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Adresse approximative"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="traffic_events/",
                        verbose_name="Photo",
                    ),
                ),
                (
                    "upvotes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Confirmations"
                    ),
                ),
                (
                    "downvotes",
                    models.PositiveIntegerField(default=0, verbose_name="Infirmations"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="L'événement sera masqué après cette date",
                        verbose_name="Expire à",
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Résolu à"
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reported_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Signalé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement trafic",
                "verbose_name_plural": "Événements trafic",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrafficEventVote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_upvote", models.BooleanField(verbose_name="Confirme ?")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="logistics.trafficevent",
                        verbose_name="Événement",
                    ),
                ),
                (
                    "voter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_votes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Votant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vote événement",
                "verbose_name_plural": "Votes événements",
            },
        ),
        migrations.AddIndex(
            model_name="trafficevent",
            index=models.Index(
                fields=["is_active", "expires_at"],
                name="logistics_t_is_acti_fbd06c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trafficevent",
            index=models.Index(
                fields=["event_type", "is_active"],
                name="logistics_t_event_t_9cab06_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="trafficeventvote",
            unique_together={("event", "voter")},
        ),
    ]
