# Generated by Django 5.2.11 on 2026-02-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_traffic_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('ASSIGNED', 'Coursier assigné'), ('EN_ROUTE_PICKUP', 'En route pour le retrait'), ('ARRIVED_PICKUP', 'Arrivé au retrait'), ('PICKED_UP', 'Colis récupéré'), ('IN_TRANSIT', 'En transit'), ('ARRIVED_DROPOFF', 'Arrivé à la livraison'), ('COMPLETED', 'Livré'), ('CANCELLED', 'Annulé'), ('FAILED', 'Échec livraison')], default='PENDING', max_length=20, verbose_name='Statut'),
        ),
    ]
