# Generated by Django 5.2.11 on 2026-02-11 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_alter_delivery_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_radius_km', models.FloatField(default=3.0, help_text='Rayon de recherche initial pour trouver des coursiers', verbose_name='Rayon initial (km)')),
                ('max_radius_km', models.FloatField(default=10.0, help_text='Rayon maximum de recherche si pas assez de coursiers', verbose_name='Rayon maximum (km)')),
                ('radius_increment_km', models.FloatField(default=2.0, help_text='De combien augmenter le rayon à chaque itération', verbose_name='Incrément rayon (km)')),
                ('max_couriers_to_score', models.PositiveIntegerField(default=20, help_text='Nombre maximum de coursiers à scorer par commande', verbose_name='Max coursiers à évaluer')),
                ('max_couriers_to_notify', models.PositiveIntegerField(default=5, help_text='Nombre de meilleurs coursiers qui recevront la notification', verbose_name='Max coursiers à notifier')),
                ('weight_distance', models.FloatField(default=0.25, help_text='Proximité au point de pickup (0.0 à 1.0)', verbose_name='⚖️ Poids : Distance')),
                ('weight_rating', models.FloatField(default=0.2, help_text='Note /5 donnée par les clients (0.0 à 1.0)', verbose_name='⚖️ Poids : Note moyenne')),
                ('weight_history', models.FloatField(default=0.15, help_text='Taux de livraisons réussies sur 30 jours (0.0 à 1.0)', verbose_name='⚖️ Poids : Historique')),
                ('weight_availability', models.FloatField(default=0.1, help_text='Temps écoulé depuis la dernière course (0.0 à 1.0)', verbose_name='⚖️ Poids : Disponibilité')),
                ('weight_financial', models.FloatField(default=0.1, help_text='Ratio dette/plafond (0.0 à 1.0)', verbose_name='⚖️ Poids : Santé financière')),
                ('weight_response', models.FloatField(default=0.05, help_text="Rapidité moyenne d'acceptation des courses (0.0 à 1.0)", verbose_name='⚖️ Poids : Temps réponse')),
                ('weight_level', models.FloatField(default=0.1, help_text='Bonus basé sur le niveau de gamification (0.0 à 1.0)', verbose_name='⚖️ Poids : Niveau coursier')),
                ('weight_acceptance', models.FloatField(default=0.05, help_text='Pourcentage de courses acceptées vs refusées (0.0 à 1.0)', verbose_name="⚖️ Poids : Taux d'acceptation")),
                ('min_score_threshold', models.FloatField(default=30.0, help_text="Score en dessous duquel un coursier n'est pas considéré (0-100)", verbose_name='Score minimum')),
                ('auto_assign_threshold', models.FloatField(default=80.0, help_text='Score au-dessus duquel le meilleur coursier est assigné automatiquement (0-100)', verbose_name="Seuil d'auto-assignation")),
                ('distance_perfect_km', models.FloatField(default=0.5, help_text='Distance en dessous de laquelle le score distance = 100', verbose_name='Distance parfaite (km)')),
                ('distance_zero_km', models.FloatField(default=8.0, help_text='Distance au-dessus de laquelle le score distance = 0', verbose_name='Distance nulle (km)')),
                ('min_ratings_for_full_score', models.PositiveIntegerField(default=10, help_text='Nombre minimum de notes pour que le score rating soit fiable (sinon score neutre)', verbose_name='Nb min de notes')),
                ('level_score_bronze', models.FloatField(default=25.0, help_text='Score attribué aux coursiers BRONZE (0-100)', verbose_name='Score niveau Bronze')),
                ('level_score_silver', models.FloatField(default=50.0, help_text='Score attribué aux coursiers SILVER (0-100)', verbose_name='Score niveau Silver')),
                ('level_score_gold', models.FloatField(default=80.0, help_text='Score attribué aux coursiers GOLD (0-100)', verbose_name='Score niveau Gold')),
                ('level_score_platinum', models.FloatField(default=100.0, help_text='Score attribué aux coursiers PLATINUM (0-100)', verbose_name='Score niveau Platinum')),
                ('streak_bonus_enabled', models.BooleanField(default=True, help_text='Ajouter un bonus au score si le coursier a une série de succès active', verbose_name='Bonus streak activé')),
                ('streak_bonus_per_delivery', models.FloatField(default=0.5, help_text='Points bonus ajoutés par livraison consécutive réussie (max 10 pts)', verbose_name='Bonus par livraison streak')),
                ('streak_bonus_max', models.FloatField(default=10.0, help_text='Bonus maximum attribuable via le streak', verbose_name='Bonus streak maximum')),
                ('probation_penalty', models.FloatField(default=15.0, help_text='Points retirés du score total pour les coursiers en probation', verbose_name='Pénalité probation')),
                ('courier_stats_cache_ttl', models.PositiveIntegerField(default=300, help_text='Durée du cache pour les statistiques des coursiers (en secondes)', verbose_name='Cache stats coursier (sec)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('notes', models.TextField(blank=True, help_text='Notes internes sur les changements effectués', verbose_name='Notes admin')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Configuration du dispatch',
                'verbose_name_plural': 'Configuration du dispatch',
            },
        ),
    ]
