# Generated by Codex on 2026-05-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0008_add_dispatch_configuration'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.UniqueConstraint(
                fields=('shop', 'external_order_id'),
                condition=(
                    models.Q(('shop__isnull', False)) &
                    models.Q(('external_order_id', ''), _negated=True)
                ),
                name='unique_shop_external_order_delivery',
            ),
        ),
    ]
