# Generated by Django 5.2.11 on 2026-02-03 17:34

import django.contrib.gis.db.models.fields
import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=15,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Format: +237XXXXXXXXX (9 chiffres après +237)",
                                regex="^\\+237[0-9]{9}$",
                            )
                        ],
                        verbose_name="Numéro WhatsApp",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Nom complet"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Administrateur"),
                            ("CLIENT", "Client Particulier"),
                            ("COURIER", "Coursier"),
                            ("BUSINESS", "E-commerçant"),
                        ],
                        default="CLIENT",
                        max_length=20,
                        verbose_name="Rôle",
                    ),
                ),
                (
                    "last_location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        null=True,
                        srid=4326,
                        verbose_name="Dernière position GPS",
                    ),
                ),
                ("last_location_updated", models.DateTimeField(blank=True, null=True)),
                (
                    "wallet_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Solde Wallet (XAF)",
                    ),
                ),
                (
                    "debt_ceiling",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("2500.00"),
                        max_digits=10,
                        verbose_name="Plafond dette (XAF)",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, verbose_name="Documents vérifiés"
                    ),
                ),
                (
                    "cni_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="documents/cni/",
                        verbose_name="Photo CNI",
                    ),
                ),
                (
                    "moto_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="documents/moto/",
                        verbose_name="Photo Moto",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
                "ordering": ["-date_joined"],
            },
        ),
    ]
