# Generated by Django 5.2.11 on 2026-02-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_business_approved",
            field=models.BooleanField(
                default=False,
                help_text="Doit être activé par l'admin pour accès aux clés API",
                verbose_name="Partenaire approuvé",
            ),
        ),
    ]
