# Generated by Django 5.2.11 on 2026-02-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_add_business_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Ex: ma-boutique → delivr.cm/book/ma-boutique",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="URL publique",
            ),
        ),
    ]
