# Generated by Django 5.2.11 on 2026-02-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_user_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="brand_color",
            field=models.CharField(
                default="#00d084",
                help_text="Code hex, ex: #00d084",
                max_length=7,
                verbose_name="Couleur principale",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="shop_logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="branding/logos/",
                verbose_name="Logo boutique",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="welcome_message",
            field=models.TextField(
                blank=True,
                help_text="Affiché sur la page de commande publique",
                verbose_name="Message de bienvenue",
            ),
        ),
    ]
