# Generated by Django 5.2.11 on 2026-02-05 14:14

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_portal_enhancements"),
        ("logistics", "0003_add_pickup_validation_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="acceptance_rate",
            field=models.FloatField(
                default=100.0,
                help_text="Pourcentage de commandes acceptées",
                verbose_name="Taux d'acceptation (%)",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="average_rating",
            field=models.FloatField(
                default=5.0, help_text="Note sur 5 étoiles", verbose_name="Note moyenne"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="average_response_seconds",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Délai moyen pour accepter une commande",
                verbose_name="Temps de réponse moyen (sec)",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="best_streak",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Meilleure série"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="cancellation_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Annulations"),
        ),
        migrations.AddField(
            model_name="user",
            name="consecutive_success_streak",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Livraisons consécutives sans incident",
                verbose_name="Série de succès",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="courier_level",
            field=models.CharField(
                choices=[
                    ("BRONZE", "Bronze"),
                    ("SILVER", "Silver"),
                    ("GOLD", "Gold"),
                    ("PLATINUM", "Platine"),
                ],
                default="BRONZE",
                max_length=20,
                verbose_name="Niveau coursier",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_online",
            field=models.BooleanField(
                default=False,
                help_text="Le coursier est-il disponible pour recevoir des commandes?",
                verbose_name="En ligne",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_online_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Dernière connexion"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="total_deliveries_completed",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Livraisons complétées"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="total_distance_km",
            field=models.FloatField(default=0.0, verbose_name="Distance totale (km)"),
        ),
        migrations.AddField(
            model_name="user",
            name="total_ratings_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Nombre d'évaluations"
            ),
        ),
        migrations.CreateModel(
            name="CourierAvailability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Lundi"),
                            (1, "Mardi"),
                            (2, "Mercredi"),
                            (3, "Jeudi"),
                            (4, "Vendredi"),
                            (5, "Samedi"),
                            (6, "Dimanche"),
                        ],
                        verbose_name="Jour de la semaine",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Heure de début")),
                ("end_time", models.TimeField(verbose_name="Heure de fin")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Ce créneau est-il actuellement actif?",
                        verbose_name="Actif",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "courier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_slots",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Coursier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disponibilité Coursier",
                "verbose_name_plural": "Disponibilités Coursiers",
                "ordering": ["day_of_week", "start_time"],
                "unique_together": {("courier", "day_of_week", "start_time")},
            },
        ),
        migrations.CreateModel(
            name="CourierBadge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "badge_type",
                    models.CharField(
                        choices=[
                            ("FIRST_DELIVERY", "Première Course 🎉"),
                            ("STREAK_10", "10 Courses Sans Annulation 🔥"),
                            ("STREAK_50", "50 Courses Sans Annulation 💪"),
                            ("STREAK_100", "100 Courses Sans Annulation 🏆"),
                            ("NIGHT_OWL", "Livreur Nocturne 🦉"),
                            ("EARLY_BIRD", "Lève-Tôt 🌅"),
                            ("SPEED_DEMON", "Temps de Réponse <2min ⚡"),
                            ("DISTANCE_100", "100 km Parcourus 🚴"),
                            ("DISTANCE_500", "500 km Parcourus 🛵"),
                            ("DISTANCE_1000", "1000 km Parcourus 🏍️"),
                            ("PERFECT_WEEK", "Semaine Parfaite ⭐"),
                            ("TOP_RATED", "Note 5 Étoiles 🌟"),
                            ("VETERAN", "500 Livraisons 🎖️"),
                            ("LEGEND", "1000 Livraisons 👑"),
                        ],
                        max_length=50,
                        verbose_name="Type de badge",
                    ),
                ),
                (
                    "earned_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'obtention"
                    ),
                ),
                (
                    "courier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badges",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Coursier",
                    ),
                ),
                (
                    "triggered_by_delivery",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="logistics.delivery",
                        verbose_name="Livraison déclencheuse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Badge Coursier",
                "verbose_name_plural": "Badges Coursiers",
                "ordering": ["-earned_at"],
                "unique_together": {("courier", "badge_type")},
            },
        ),
        migrations.CreateModel(
            name="CourierPerformanceLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "deliveries_completed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Livraisons complétées"
                    ),
                ),
                (
                    "deliveries_cancelled",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Livraisons annulées"
                    ),
                ),
                (
                    "deliveries_failed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Livraisons échouées"
                    ),
                ),
                (
                    "total_earnings",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Gains du jour (XAF)",
                    ),
                ),
                (
                    "total_commission_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Commissions payées (XAF)",
                    ),
                ),
                (
                    "total_distance_km",
                    models.FloatField(
                        default=0.0, verbose_name="Distance parcourue (km)"
                    ),
                ),
                (
                    "total_online_minutes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Temps en ligne (min)"
                    ),
                ),
                (
                    "average_response_seconds",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Temps de réponse moyen (sec)"
                    ),
                ),
                (
                    "ratings_received",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Évaluations reçues"
                    ),
                ),
                (
                    "ratings_sum",
                    models.FloatField(default=0.0, verbose_name="Somme des notes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "courier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Coursier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log Performance Coursier",
                "verbose_name_plural": "Logs Performance Coursiers",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["courier", "date"],
                        name="core_courie_courier_6a62da_idx",
                    ),
                    models.Index(fields=["date"], name="core_courie_date_0d4431_idx"),
                ],
                "unique_together": {("courier", "date")},
            },
        ),
        migrations.CreateModel(
            name="CourierZonePreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="1 = haute priorité",
                        verbose_name="Priorité",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "courier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zone_preferences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Coursier",
                    ),
                ),
                (
                    "neighborhood",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="logistics.neighborhood",
                        verbose_name="Quartier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Préférence Zone Coursier",
                "verbose_name_plural": "Préférences Zones Coursiers",
                "ordering": ["priority"],
                "unique_together": {("courier", "neighborhood")},
            },
        ),
    ]
