# Generated by Django 5.2.11 on 2026-02-05 19:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_user_acceptance_rate_user_average_rating_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SMSOTPLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=15, verbose_name="Numéro"),
                ),
                ("otp_code", models.CharField(max_length=6, verbose_name="Code OTP")),
                (
                    "provider",
                    models.CharField(
                        help_text="ORANGE_CM, MTN_CM, ou WHATSAPP",
                        max_length=20,
                        verbose_name="Opérateur",
                    ),
                ),
                (
                    "provider_message_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ID message opérateur"
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(verbose_name="Expire à")),
                ("verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "attempts",
                    models.PositiveIntegerField(default=0, verbose_name="Tentatives"),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Log OTP SMS",
                "verbose_name_plural": "Logs OTP SMS",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="onboarding_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Documents en attente"),
                    ("PROBATION", "Période d'essai"),
                    ("APPROVED", "Approuvé"),
                    ("REJECTED", "Rejeté"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="Statut onboarding",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="probation_deliveries_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Livraisons pendant probation"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="probation_delivery_limit",
            field=models.PositiveIntegerField(
                default=10, verbose_name="Limite livraisons/jour (probation)"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="probation_end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fin période d'essai"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="probation_start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Début période d'essai"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="trust_score",
            field=models.FloatField(
                default=0.5,
                help_text="0.0 à 1.0, calculé automatiquement",
                verbose_name="Score de confiance",
            ),
        ),
        migrations.CreateModel(
            name="CourierOnboarding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "current_step",
                    models.CharField(
                        choices=[
                            ("PHONE_VERIFIED", "Téléphone vérifié"),
                            ("DOCS_UPLOADED", "Documents soumis"),
                            ("EMERGENCY", "Contact d'urgence"),
                            ("CAUTION", "Caution payée"),
                            ("CONTRACT", "Contrat signé"),
                            ("VALIDATED", "Validé par admin"),
                            ("PROBATION", "Période probatoire"),
                            ("COMPLETED", "Onboarding terminé"),
                        ],
                        default="PHONE_VERIFIED",
                        max_length=20,
                        verbose_name="Étape actuelle",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En cours"),
                            ("AWAITING", "En attente de validation"),
                            ("APPROVED", "Approuvé"),
                            ("REJECTED", "Rejeté"),
                            ("SUSPENDED", "Suspendu"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Statut global",
                    ),
                ),
                (
                    "phone_verified",
                    models.BooleanField(
                        default=False, verbose_name="Téléphone vérifié"
                    ),
                ),
                (
                    "phone_otp_code",
                    models.CharField(blank=True, max_length=6, verbose_name="Code OTP"),
                ),
                ("phone_otp_sent_at", models.DateTimeField(blank=True, null=True)),
                ("phone_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cni_front",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="onboarding/cni/front/",
                        verbose_name="CNI Recto",
                    ),
                ),
                (
                    "cni_back",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="onboarding/cni/back/",
                        verbose_name="CNI Verso",
                    ),
                ),
                (
                    "cni_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Numéro CNI"
                    ),
                ),
                (
                    "cni_expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'expiration CNI"
                    ),
                ),
                (
                    "selfie_with_cni",
                    models.ImageField(
                        blank=True,
                        help_text="Photo de vous tenant votre CNI",
                        null=True,
                        upload_to="onboarding/selfies/",
                        verbose_name="Selfie avec CNI",
                    ),
                ),
                (
                    "casier_judiciaire",
                    models.FileField(
                        blank=True,
                        help_text="Doit être récent (< 3 mois)",
                        null=True,
                        upload_to="onboarding/casier/",
                        verbose_name="Casier Judiciaire (Bulletin n°3)",
                    ),
                ),
                (
                    "casier_issue_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'émission casier"
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("MOTO", "Moto"),
                            ("BICYCLE", "Vélo"),
                            ("FOOT", "À pied"),
                            ("CAR", "Voiture"),
                        ],
                        default="MOTO",
                        max_length=20,
                        verbose_name="Type de véhicule",
                    ),
                ),
                (
                    "driving_license",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="onboarding/permis/",
                        verbose_name="Permis de conduire",
                    ),
                ),
                (
                    "driving_license_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Numéro permis"
                    ),
                ),
                (
                    "driving_license_category",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Catégorie (A, B, etc.)"
                    ),
                ),
                (
                    "carte_grise",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="onboarding/carte_grise/",
                        verbose_name="Carte Grise",
                    ),
                ),
                (
                    "vehicle_plate",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Immatriculation"
                    ),
                ),
                (
                    "vehicle_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="onboarding/vehicles/",
                        verbose_name="Photo du véhicule",
                    ),
                ),
                ("documents_submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "emergency_contact_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Nom contact d'urgence"
                    ),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="Téléphone urgence"
                    ),
                ),
                (
                    "emergency_contact_relation",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Relation (Père, Mère, Époux, etc.)",
                    ),
                ),
                (
                    "home_address",
                    models.TextField(
                        blank=True,
                        help_text="Quartier, rue, repère",
                        verbose_name="Adresse domicile",
                    ),
                ),
                (
                    "home_city",
                    models.CharField(
                        blank=True,
                        default="Douala",
                        max_length=50,
                        verbose_name="Ville",
                    ),
                ),
                (
                    "caution_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=15000,
                        max_digits=10,
                        verbose_name="Montant caution (XAF)",
                    ),
                ),
                (
                    "caution_paid",
                    models.BooleanField(default=False, verbose_name="Caution payée"),
                ),
                (
                    "caution_payment_method",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Méthode paiement (MOMO, ORANGE, CASH)",
                    ),
                ),
                (
                    "caution_transaction_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="ID transaction caution",
                    ),
                ),
                ("caution_paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "contract_version",
                    models.CharField(
                        default="v1.0", max_length=20, verbose_name="Version contrat"
                    ),
                ),
                (
                    "contract_signed",
                    models.BooleanField(default=False, verbose_name="Contrat signé"),
                ),
                ("contract_signed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "signature_data",
                    models.TextField(
                        blank=True,
                        verbose_name="Signature (Base64 ou texte acceptation)",
                    ),
                ),
                (
                    "contract_ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP signature"
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, verbose_name="Notes admin"),
                ),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Motif de rejet"),
                ),
                (
                    "probation_deliveries_required",
                    models.PositiveIntegerField(
                        default=10, verbose_name="Livraisons probatoires requises"
                    ),
                ),
                (
                    "probation_deliveries_completed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Livraisons probatoires complétées"
                    ),
                ),
                ("probation_started_at", models.DateTimeField(blank=True, null=True)),
                ("probation_completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "courier",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Coursier",
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validated_onboardings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Validé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Onboarding Coursier",
                "verbose_name_plural": "Onboardings Coursiers",
                "ordering": ["-created_at"],
            },
        ),
    ]
