# Generated by Django 5.2.11 on 2026-02-08 04:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_add_onboarding_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Code unique, ex: BIENVENUE2025",
                        max_length=30,
                        unique=True,
                        verbose_name="Code promo",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("PERCENTAGE", "Pourcentage (%)"),
                            ("FIXED", "Montant fixe (XAF)"),
                        ],
                        default="PERCENTAGE",
                        max_length=20,
                        verbose_name="Type de remise",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Pourcentage (ex: 10) ou montant fixe (ex: 500)",
                        max_digits=10,
                        verbose_name="Valeur",
                    ),
                ),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="0 = illimité",
                        verbose_name="Utilisations max",
                    ),
                ),
                (
                    "current_uses",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Utilisations actuelles"
                    ),
                ),
                (
                    "min_order_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Montant minimum commande (XAF)",
                    ),
                ),
                (
                    "max_discount_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Plafond pour les remises en pourcentage",
                        max_digits=10,
                        null=True,
                        verbose_name="Remise max (XAF)",
                    ),
                ),
                ("valid_from", models.DateTimeField(verbose_name="Valide à partir de")),
                ("valid_until", models.DateTimeField(verbose_name="Valide jusqu'au")),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_promos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Code promo",
                "verbose_name_plural": "Codes promo",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdminActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Création"),
                            ("UPDATE", "Modification"),
                            ("DELETE", "Suppression"),
                            ("APPROVE", "Approbation"),
                            ("REJECT", "Rejet"),
                            ("BLOCK", "Blocage"),
                            ("UNBLOCK", "Déblocage"),
                            ("EXPORT", "Export"),
                            ("IMPORT", "Import"),
                            ("LOGIN", "Connexion admin"),
                        ],
                        max_length=20,
                        verbose_name="Action",
                    ),
                ),
                (
                    "target_model",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Modèle cible"
                    ),
                ),
                (
                    "target_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ID cible"
                    ),
                ),
                (
                    "details",
                    models.JSONField(blank=True, default=dict, verbose_name="Détails"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_activity_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Administrateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log d'activité admin",
                "verbose_name_plural": "Logs d'activité admin",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="core_admina_user_id_14c2f6_idx",
                    ),
                    models.Index(
                        fields=["action", "created_at"],
                        name="core_admina_action_f8c915_idx",
                    ),
                    models.Index(
                        fields=["target_model", "created_at"],
                        name="core_admina_target__34390f_idx",
                    ),
                ],
            },
        ),
    ]
