# Generated by Django 5.2.11 on 2026-02-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_admin_activity_log_and_promo_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="business_type",
            field=models.CharField(
                choices=[
                    ("SOCIAL", "Réseaux Sociaux (Instagram, FB, WA)"),
                    ("WEB", "Site Web (WooCommerce, Shopify...)"),
                ],
                default="SOCIAL",
                max_length=20,
                verbose_name="Type de business",
            ),
        ),
    ]
