# Generated by Django 5.2.11 on 2026-02-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_user_business_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="business_type",
            field=models.CharField(
                choices=[
                    ("SOCIAL", "Réseaux Sociaux (Instagram, FB, WA)"),
                    ("WEB", "Site Web (WooCommerce, Shopify...)"),
                    ("BOTH", "Les deux (Réseaux Sociaux & Site Web)"),
                ],
                default="SOCIAL",
                max_length=20,
                verbose_name="Type de business",
            ),
        ),
    ]
