# Generated by Django 5.2.11 on 2026-02-03 17:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("logistics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("DEPOSIT", "Dépôt"),
                            ("DELIVERY_CREDIT", "Crédit livraison"),
                            ("REFUND", "Remboursement"),
                            ("COMMISSION", "Commission plateforme"),
                            ("WITHDRAWAL", "Retrait"),
                            ("PREPAID_DEBIT", "Débit prépayé"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Montant (XAF)"
                    ),
                ),
                (
                    "balance_before",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Solde avant"
                    ),
                ),
                (
                    "balance_after",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Solde après"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("COMPLETED", "Confirmé"),
                            ("FAILED", "Échoué"),
                            ("REVERSED", "Annulé"),
                        ],
                        default="COMPLETED",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Description"
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Référence externe"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "delivery",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="logistics.delivery",
                        verbose_name="Livraison liée",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="finance_tra_user_id_21480b_idx",
                    ),
                    models.Index(
                        fields=["transaction_type", "status"],
                        name="finance_tra_transac_4d20c4_idx",
                    ),
                ],
            },
        ),
    ]
