# Generated by Django 5.2.11 on 2026-02-05 15:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WithdrawalRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Montant (XAF)"
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("MTN_MOMO", "MTN Mobile Money"),
                            ("ORANGE_MONEY", "Orange Money"),
                        ],
                        max_length=20,
                        verbose_name="Fournisseur",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Numéro Mobile Money"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("PROCESSING", "En cours"),
                            ("COMPLETED", "Terminé"),
                            ("FAILED", "Échoué"),
                            ("REJECTED", "Rejeté"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "external_transaction_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="ID Transaction Mobile Money",
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Raison du rejet"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "courier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="withdrawal_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Coursier",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_withdrawals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Traité par",
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="withdrawal_request",
                        to="finance.transaction",
                        verbose_name="Transaction associée",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de retrait",
                "verbose_name_plural": "Demandes de retrait",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["courier", "status"],
                        name="finance_wit_courier_1826c5_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="finance_wit_status_331b0d_idx",
                    ),
                ],
            },
        ),
    ]
