# Generated by Django 5.2.11 on 2026-02-05 18:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_withdrawalrequest"),
        ("logistics", "0003_add_pickup_validation_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Numéro de facture"
                    ),
                ),
                (
                    "invoice_type",
                    models.CharField(
                        choices=[
                            ("DELIVERY_RECEIPT", "Reçu de livraison"),
                            ("COURIER_STATEMENT", "Relevé coursier"),
                            ("B2B_INVOICE", "Facture partenaire"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Montant total (XAF)",
                    ),
                ),
                (
                    "period_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="Début période"
                    ),
                ),
                (
                    "period_end",
                    models.DateField(blank=True, null=True, verbose_name="Fin période"),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="invoices/%Y/%m/",
                        verbose_name="Fichier PDF",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "delivery",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="logistics.delivery",
                        verbose_name="Livraison liée",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facture",
                "verbose_name_plural": "Factures",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "invoice_type"],
                        name="finance_inv_user_id_27560f_idx",
                    ),
                    models.Index(
                        fields=["invoice_number"], name="finance_inv_invoice_89da8a_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="finance_inv_created_6e1634_idx"
                    ),
                ],
            },
        ),
    ]
