# Generated by Django 5.2.11 on 2026-02-05 21:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_add_invoice_model"),
        ("logistics", "0005_add_mobile_payment"),
    ]

    operations = [
        migrations.CreateModel(
            name="MobilePayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("MTN", "MTN Mobile Money"), ("OM", "Orange Money")],
                        max_length=10,
                        verbose_name="Opérateur",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=15, verbose_name="Numéro payeur"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Montant (XAF)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("SUCCESSFUL", "Réussi"),
                            ("FAILED", "Échoué"),
                            ("CANCELLED", "Annulé"),
                            ("TIMEOUT", "Expiré"),
                            ("REJECTED", "Rejeté"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "external_reference",
                    models.CharField(
                        help_text="Notre UUID pour cette transaction",
                        max_length=100,
                        unique=True,
                        verbose_name="Référence externe",
                    ),
                ),
                (
                    "provider_transaction_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="ID transaction opérateur",
                    ),
                ),
                (
                    "pay_token",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Pay Token"
                    ),
                ),
                (
                    "payment_url",
                    models.URLField(blank=True, verbose_name="URL de paiement"),
                ),
                ("error_code", models.CharField(blank=True, max_length=50)),
                ("error_message", models.TextField(blank=True)),
                ("callback_received", models.BooleanField(default=False)),
                ("callback_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mobile_payments",
                        to="logistics.delivery",
                        verbose_name="Livraison",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement Mobile",
                "verbose_name_plural": "Paiements Mobile",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["external_reference"],
                        name="finance_mob_externa_2b6b8a_idx",
                    ),
                    models.Index(
                        fields=["delivery", "status"],
                        name="finance_mob_deliver_0a16ea_idx",
                    ),
                    models.Index(
                        fields=["provider", "status"],
                        name="finance_mob_provide_eb7dd1_idx",
                    ),
                ],
            },
        ),
    ]
