# Generated by Django 5.2.11 on 2026-02-05 08:24

import django.db.models.deletion
import secrets
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True, help_text="URL to receive webhook POST requests"
                    ),
                ),
                (
                    "secret",
                    models.CharField(
                        default=secrets.token_hex,
                        help_text="HMAC secret for signature verification",
                        max_length=64,
                    ),
                ),
                (
                    "events",
                    models.JSONField(
                        default=list, help_text="List of event types to subscribe to"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, help_text="Enable/disable webhook"
                    ),
                ),
                ("last_triggered", models.DateTimeField(blank=True, null=True)),
                ("last_status_code", models.IntegerField(blank=True, null=True)),
                ("failure_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_config",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration Webhook",
                "verbose_name_plural": "Configurations Webhook",
            },
        ),
    ]
