# Generated by Django 5.2.11 on 2026-02-08 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0005_add_mobile_payment"),
        ("partners", "0001_portal_enhancements"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("order_created", "Nouvelle commande"),
                            ("order_assigned", "Coursier assigné"),
                            ("order_picked_up", "Colis récupéré"),
                            ("order_completed", "Livraison terminée"),
                            ("order_cancelled", "Commande annulée"),
                            ("payment_received", "Paiement reçu"),
                            ("invoice_generated", "Facture générée"),
                            ("system", "Système"),
                        ],
                        default="system",
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "delivery",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="partner_notifications",
                        to="logistics.delivery",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Partenaire",
                "verbose_name_plural": "Notifications Partenaires",
                "ordering": ["-created_at"],
            },
        ),
    ]
