# Generated by Django 5.2.11 on 2026-02-10 18:00

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0004_add_mobile_payment'),
        ('logistics', '0006_traffic_events'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('ITEM_NOT_RECEIVED', 'Colis non reçu'), ('ITEM_DAMAGED', 'Colis endommagé'), ('ITEM_MISMATCH', 'Contenu non conforme'), ('OVERCHARGED', 'Surfacturation'), ('COURIER_CONDUCT', 'Comportement du coursier'), ('OTHER', 'Autre')], max_length=50, verbose_name='Raison')),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('INVESTIGATING', "En cours d'investigation"), ('RESOLVED', 'Résolu'), ('REJECTED', 'Rejeté'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('photo_evidence', models.ImageField(blank=True, null=True, upload_to='disputes/evidence/', verbose_name='Preuve photo')),
                ('resolution_note', models.TextField(blank=True, verbose_name='Note de résolution')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Montant remboursé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_disputes', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='logistics.delivery', verbose_name='Livraison')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL, verbose_name='Résolu par')),
            ],
            options={
                'verbose_name': 'Litige',
                'verbose_name_plural': 'Litiges',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('COMPLETED', 'Effectué'), ('FAILED', 'Échoué')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('reason', models.TextField(blank=True, verbose_name='Raison du remboursement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('dispute', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refund', to='support.dispute', verbose_name='Litige')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_record', to='finance.transaction', verbose_name='Transaction liée')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to=settings.AUTH_USER_MODEL, verbose_name='Bénéficiaire')),
            ],
            options={
                'verbose_name': 'Remboursement',
                'verbose_name_plural': 'Remboursements',
                'ordering': ['-created_at'],
            },
        ),
    ]
