# Generated by Django 5.2.11 on 2026-02-11 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_sender_order_created', models.BooleanField(default=True, help_text="Envoyer confirmation + codes OTP à l'expéditeur", verbose_name='📤 Expéditeur → Commande créée')),
                ('msg_sender_order_created', models.TextField(blank=True, help_text='Variables disponibles : {ref}, {price}, {distance}, {pickup_otp}, {delivery_otp}, {tracking_url}, {recipient_name}', verbose_name='Message personnalisé')),
                ('notify_recipient_order_created', models.BooleanField(default=True, help_text='Envoyer le code OTP de livraison au destinataire', verbose_name='📥 Destinataire → Commande créée')),
                ('msg_recipient_order_created', models.TextField(blank=True, help_text='Variables : {ref}, {sender_name}, {otp}, {tracking_url}', verbose_name='Message personnalisé')),
                ('notify_sender_assigned', models.BooleanField(default=True, help_text="Notifier l'expéditeur qu'un coursier a accepté", verbose_name='📤 Expéditeur → Coursier assigné')),
                ('msg_sender_assigned', models.TextField(blank=True, help_text='Variables : {ref}, {courier_name}, {courier_phone}, {tracking_url}', verbose_name='Message personnalisé')),
                ('notify_recipient_assigned', models.BooleanField(default=True, help_text="Informer le destinataire qu'un coursier est en route", verbose_name='📥 Destinataire → Coursier assigné')),
                ('msg_recipient_assigned', models.TextField(blank=True, help_text='Variables : {ref}, {courier_name}, {tracking_url}', verbose_name='Message personnalisé')),
                ('notify_sender_en_route_pickup', models.BooleanField(default=True, help_text='Le coursier part vers le lieu de ramassage', verbose_name='📤 Expéditeur → En route pickup')),
                ('msg_sender_en_route_pickup', models.TextField(blank=True, help_text='Variables : {ref}, {courier_name}, {tracking_url}', verbose_name='Message personnalisé')),
                ('notify_recipient_en_route_pickup', models.BooleanField(default=False, help_text='Informer le destinataire que le coursier va chercher le colis', verbose_name='📥 Destinataire → En route pickup')),
                ('notify_sender_arrived_pickup', models.BooleanField(default=True, help_text='Le coursier est arrivé au point de ramassage', verbose_name='📤 Expéditeur → Arrivé au pickup')),
                ('msg_sender_arrived_pickup', models.TextField(blank=True, help_text='Variables : {ref}, {courier_name}, {pickup_otp}', verbose_name='Message personnalisé')),
                ('notify_recipient_arrived_pickup', models.BooleanField(default=False, help_text='Informer le destinataire que le coursier est au point de retrait', verbose_name='📥 Destinataire → Arrivé au pickup')),
                ('notify_sender_picked_up', models.BooleanField(default=True, help_text='Le coursier a récupéré le colis', verbose_name='📤 Expéditeur → Colis récupéré')),
                ('msg_sender_picked_up', models.TextField(blank=True, help_text='Variables : {ref}, {courier_name}, {recipient_name}, {tracking_url}', verbose_name='Message personnalisé')),
                ('notify_recipient_picked_up', models.BooleanField(default=True, help_text='Informer le destinataire que le colis est en préparation de livraison', verbose_name='📥 Destinataire → Colis récupéré')),
                ('msg_recipient_picked_up', models.TextField(blank=True, help_text='Variables : {ref}, {sender_name}, {courier_name}, {tracking_url}', verbose_name='Message personnalisé')),
                ('notify_sender_in_transit', models.BooleanField(default=True, help_text='Le colis est en route vers la destination', verbose_name='📤 Expéditeur → En transit')),
                ('msg_sender_in_transit', models.TextField(blank=True, help_text='Variables : {ref}, {courier_name}, {tracking_url}', verbose_name='Message personnalisé')),
                ('notify_recipient_in_transit', models.BooleanField(default=True, help_text='Rappeler le code OTP au destinataire + le colis arrive bientôt', verbose_name='📥 Destinataire → En transit')),
                ('msg_recipient_in_transit', models.TextField(blank=True, help_text='Variables : {ref}, {sender_name}, {otp}, {tracking_url}', verbose_name='Message personnalisé')),
                ('notify_sender_arrived_dropoff', models.BooleanField(default=True, help_text='Le coursier est arrivé chez le destinataire', verbose_name='📤 Expéditeur → Arrivé destination')),
                ('msg_sender_arrived_dropoff', models.TextField(blank=True, help_text='Variables : {ref}, {courier_name}, {recipient_name}', verbose_name='Message personnalisé')),
                ('notify_recipient_arrived_dropoff', models.BooleanField(default=True, help_text='Prévenir le destinataire que le coursier est à sa porte', verbose_name='📥 Destinataire → Arrivé destination')),
                ('msg_recipient_arrived_dropoff', models.TextField(blank=True, help_text='Variables : {ref}, {courier_name}, {otp}', verbose_name='Message personnalisé')),
                ('notify_sender_completed', models.BooleanField(default=True, help_text="Confirmation de livraison réussie à l'expéditeur", verbose_name='📤 Expéditeur → Livraison terminée')),
                ('msg_sender_completed', models.TextField(blank=True, help_text='Variables : {ref}, {recipient_name}, {price}, {distance}, {tracking_url}', verbose_name='Message personnalisé')),
                ('notify_recipient_completed', models.BooleanField(default=True, help_text='Confirmation + reçu PDF au destinataire', verbose_name='📥 Destinataire → Livraison terminée')),
                ('msg_recipient_completed', models.TextField(blank=True, help_text='Variables : {ref}, {sender_name}', verbose_name='Message personnalisé')),
                ('notify_sender_cancelled', models.BooleanField(default=True, help_text="Notifier l'expéditeur de l'annulation", verbose_name='📤 Expéditeur → Commande annulée')),
                ('msg_sender_cancelled', models.TextField(blank=True, help_text='Variables : {ref}, {reason}', verbose_name='Message personnalisé')),
                ('notify_recipient_cancelled', models.BooleanField(default=True, help_text="Notifier le destinataire de l'annulation", verbose_name='📥 Destinataire → Commande annulée')),
                ('msg_recipient_cancelled', models.TextField(blank=True, help_text='Variables : {ref}, {sender_name}', verbose_name='Message personnalisé')),
                ('notify_sender_failed', models.BooleanField(default=True, help_text="Notifier l'expéditeur de l'échec", verbose_name='📤 Expéditeur → Livraison échouée')),
                ('msg_sender_failed', models.TextField(blank=True, help_text='Variables : {ref}', verbose_name='Message personnalisé')),
                ('notify_recipient_failed', models.BooleanField(default=True, help_text="Notifier le destinataire de l'échec", verbose_name='📥 Destinataire → Livraison échouée')),
                ('msg_recipient_failed', models.TextField(blank=True, help_text='Variables : {ref}, {sender_name}', verbose_name='Message personnalisé')),
                ('notify_dispute_updates', models.BooleanField(default=True, help_text='Notifier le créateur du litige des mises à jour', verbose_name='⚖️ Mises à jour litiges')),
                ('notify_daily_summary', models.BooleanField(default=True, help_text='Envoyer un résumé des revenus du jour aux coursiers', verbose_name='📊 Résumé quotidien coursiers')),
                ('notify_rating_request', models.BooleanField(default=True, help_text='Demander au client de noter la livraison après complétion', verbose_name='⭐ Demande de note')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('notes', models.TextField(blank=True, help_text='Notes internes sur les changements effectués', verbose_name='Notes admin')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Configuration des notifications',
                'verbose_name_plural': 'Configuration des notifications',
            },
        ),
    ]
