# Generated by Django 5.2.11 on 2026-02-04 22:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "active_whatsapp_provider",
                    models.CharField(
                        choices=[("twilio", "Twilio"), ("meta", "Meta Cloud API")],
                        default="twilio",
                        help_text="Sélectionnez le provider pour les notifications WhatsApp",
                        max_length=20,
                        verbose_name="Provider WhatsApp actif",
                    ),
                ),
                (
                    "twilio_whatsapp_number",
                    models.CharField(
                        default="whatsapp:+14155238886",
                        help_text="Format: whatsapp:+XXXXXXXXXXX",
                        max_length=50,
                        verbose_name="Numéro WhatsApp Twilio",
                    ),
                ),
                (
                    "meta_phone_number_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ID du numéro de téléphone dans Meta Business",
                        max_length=50,
                        verbose_name="Phone Number ID Meta",
                    ),
                ),
                (
                    "meta_verify_token",
                    models.CharField(
                        default="delivr-cm-webhook-verify-token",
                        help_text="Token utilisé pour vérifier les webhooks Meta",
                        max_length=100,
                        verbose_name="Token de vérification Meta",
                    ),
                ),
                (
                    "pricing_base_fare",
                    models.PositiveIntegerField(
                        default=500,
                        help_text="Montant de base pour toute livraison",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Tarif de base (FCFA)",
                    ),
                ),
                (
                    "pricing_cost_per_km",
                    models.PositiveIntegerField(
                        default=150,
                        help_text="Coût additionnel par kilomètre parcouru",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Coût par kilomètre (FCFA)",
                    ),
                ),
                (
                    "pricing_minimum_fare",
                    models.PositiveIntegerField(
                        default=1000,
                        help_text="Prix plancher pour toute livraison",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Tarif minimum (FCFA)",
                    ),
                ),
                (
                    "platform_fee_percent",
                    models.PositiveIntegerField(
                        default=20,
                        help_text="Pourcentage prélevé par la plateforme sur chaque livraison",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Commission plateforme (%)",
                    ),
                ),
                (
                    "courier_debt_ceiling",
                    models.PositiveIntegerField(
                        default=2500,
                        help_text="Montant maximum de dette autorisé avant blocage",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Plafond dette coursier (FCFA)",
                    ),
                ),
                (
                    "osrm_base_url",
                    models.URLField(
                        default="http://osrm:5000",
                        help_text="URL du service de routing OSRM",
                        verbose_name="URL OSRM",
                    ),
                ),
                (
                    "nominatim_base_url",
                    models.URLField(
                        default="http://nominatim:8080",
                        help_text="URL du service de géocodage Nominatim",
                        verbose_name="URL Nominatim",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière modification"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="integration_config_updates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration des Intégrations",
                "verbose_name_plural": "Configuration des Intégrations",
            },
        ),
    ]
